Update hello.yml

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -1,37 +1,34 @@
-# This is a basic workflow to help you get started with Actions
+name: Auto Merge and Notify
 
-name: CI
-
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the master branch
   push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
+    branches:
+      - master
 
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  merge_and_notify:
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
+    env:
+      TARGET_BRANCH: test_branch_name
+
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, SDK!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        if: false
+      - name: Merge changes
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          git fetch origin
+          git checkout $TARGET_BRANCH
+          git pull origin $TARGET_BRANCH
+          git merge ${{ github.ref }}
+          git push origin $TARGET_BRANCH || { echo "Merge failed"; exit 1; }
+
+      - name: Send Slack notification on failure
+        if: failure()
+        uses: slack/send-message-action@v2
+        with:
+          channel: your_slack_channel
+          text: "Failed to merge branch '${{ github.ref }}' into $TARGET_BRANCH"
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
